name: dasic
version: 1.1.1
description: Dasic is a complete standalone interpreter for a dialect of the original BASIC language.
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-dasic

environment:
  sdk: ">=2.0.0 <3.0.0"

# Add the bin/dasic.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  dasic:

dependencies:

  validate: ^1.0.0

  console_log_handler: ^1.0.0
  # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  args: ^1.4.0
  yaml: ^2.1.0

dev_dependencies:
  test: any
  grinder: any

  build_runner: any
  build_test: any
