name: dasic
version: 1.1.0
description: Dasic is a complete standalone interpreter for a dialect of the original BASIC language.
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-dasic

environment:
  sdk: ">=1.8.0 <2.0.0"

# Add the bin/dasic.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  dasic:

dependencies:
  browser: ^0.10.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.2.0

  validate:   ^1.0.0

  args: ^0.13.0
  yaml: ^2.1.0

dev_dependencies:
  test: any
  grinder: any